services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://app-proyecto-sena.onrender.com

      # Configuración de base de datos (Supabase)
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: db.pqeibmfydyfbyzzcjkiq.supabase.co
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres
      - key: DB_PASSWORD
        value: proyectomara

      # Otros
      - key: SANCTUM_STATEFUL_DOMAINS
        value: https://proyecto-sena-facturacion-fronted.vercel.app
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=8000"
    deployHook: "php artisan key:generate && php artisan config:cache && php artisan route:cache && php artisan migrate --force"
