services:
  - type: web
    name: laravel-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    autoDeploy: true

    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://laravel-backend.onrender.com  # ← Usa el dominio real del backend en Render

      # Conexión a la base de datos PostgreSQL
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: dpg-d1lc1s6r433s73di8rj0-a.oregon-postgres.render.com
      - key: DB_PORT
        value: 5432
      - key: DB_DATABASE
        value: facturacion_zfai
      - key: DB_USERNAME
        value: facturacion_user
      - key: DB_PASSWORD
        value: 23Il8z4P2xp24MBrVBNAaF55jUyd4zgv

      # Configuración para Sanctum y CORS
      - key: SANCTUM_STATEFUL_DOMAINS
        value: https://proyecto-sena-facturacion-fronted.vercel.app
      - key: SESSION_DOMAIN
        value: proyecto-sena-facturacion-fronted.vercel.app
      - key: SESSION_SECURE_COOKIE
        value: true
      - key: CORS_ALLOWED_ORIGINS
        value: https://proyecto-sena-facturacion-fronted.vercel.app

    # Ejecuta migraciones después del deploy (opcional si ya se hace en el CMD del Dockerfile)
    deployHook: "php artisan migrate --force"
